import type { Metadata } from "next";
import "./globals.css";
import styles from "./layout.module.css";
import Navbar from "@/components/navbar/Navbar";
import SmoothScroll from "@/components/smoothScroll/SmoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <SmoothScroll>
          <div className="h-full flex justify-center">
            <div className="max-w-[500px] min-w-[320px] w-full h-full">
              <Navbar />
              <div className={styles.container}>{children}</div>
            </div>
          </div>
        </SmoothScroll>
      </body>
    </html>
  );
}
